apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: default #if u dont specidy they tend to just go default - namespace is just a way to organise 
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo # this label connect this service to the deployment
  
  type: ClusterIP  # also use LoadBalancer - for local use cluster IP