---
apiVersion: v1
kind: Service
metadata:
  name: ttt-svc
  namespace: default #if u dont specidy they tend to just go default - namespace is just a way to organise 
spec:
  ports:
  - nodePort: 30002 # range is 30000-32768
    port: 3000
    targetPort: 3000

  selector:
    app: ttt  # this label connect this service to the deployment
  
  type: NodePort  # also use LoadBalancer - for local use cluster IP